### ISSUE TITLE
MYSQL

### ISSUE THREAD

**Issue by SergiuCip** [obi12341/docker-pdns#2]
Hi, 

First of all thanks for creating such module! 

I am trying to use this module however, every time I am trying to create the VM it is complaining about the mysql:db that couldn't find it. 

Tried to install the MYSQL container manually and change the details in the .yml file you provide to point to my MYSQL container, and then run your docker container and attach to it and all I get it is "waiting for mysql" .

Could you please tell me what I am doing wrong?

Thanks,

Regards,
Sergiu

**Comment by obi12341** [comment]
Seems to be something wrong with your docker setup. I can't reproduce it
