### ISSUE TITLE
Can we move PowerAdmin do seperate Docker?

### ISSUE THREAD

**Issue by gintsgints** [obi12341/docker-pdns#4]
How about if we move PowerAdmin to different docker image and start it seperatly with docker-compose?

That way we could allow to combine with different guis.

**Comment by obi12341** [comment]
could be possible, but goal of this docker image is an easy setup. If you want something more environment specific, you need to build it on your own.

**Comment by gintsgints** [comment]
I see you have upgraded to newer PowerDNS. This version have own webserver and api. Are you interested on pull request for enabling API with env variables?

**Comment by obi12341** [comment]
ofc, i am happy about every PR
